import os
import sphinx_rtd_theme

# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'OpenBike'
copyright = '2020, Stadt Ulm'
author = 'Stadt Ulm: Maximilian Richt, Katharina Schweiger, Constantin Müller, Stefan Kaufmann'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.githubpages',
    'sphinx_rtd_theme',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

html_theme_options = {
    'logo_only': True,
    'display_version': False,
    'prev_next_buttons_location': 'bottom',
    'collapse_navigation': False,
}

html_show_sourcelink = False

html_context = {
    'display_github': True,
    'github_user': 'stadtulm',
    'github_repo': 'openbike',
    'github_version': 'master',
    'conf_py_path': '/docs/', # needs leading and trailing slashes!
}

html_logo = 'images/openbike-white.svg'

html_css_files = [
    'css/custom.css',
]

html_additional_pages = {
    'index': 'index.html'
}

def force_rerender(app, env, added, changed, removed):
    return ['index']

def setup(app):
    app.add_css_file('css/custom.css')
    if 'LIVEBUILD' in os.environ:
    	print('Enabling force rerender for static files')
    	app.connect('env-get-outdated', force_rerender)

html_show_copyright = False

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
